from src.core.XVar import XVar
import random


def close_window(xvar: XVar) -> None:
    """Close the MLX window and terminate the MLX loop."""
    xvar.mlx.mlx_destroy_window(xvar.mlx_ptr, xvar.window)
    xvar.mlx.mlx_release(xvar.mlx_ptr)
    xvar.mlx.mlx_loop_exit(xvar.mlx_ptr)


def gere_key(key: int, xvar: XVar) -> None:
    """Handle keyboard input and trigger maze regeneration or color changes."""
    if not xvar.finish_render:
        return

    assert xvar.algorithm is not None
    if key == 104:  # 'h'
        xvar.algorithm.draw_generation = xvar.algorithm.draw_shortest_path(
            0xFFFFFFFF
        )

    elif key == 112:  # 'p'
        xvar.algorithm.draw_generation = xvar.algorithm.draw_shortest_path(
            0xFF0FFFFF
        )

    elif key == 115:  # 's'
        while True:
            try:
                xvar.seed = int(input("Enter a seed: "))
                break
            except Exception:
                print("Seed must be an integer number!")
        key = 114

    elif key == 99:  # 'c'
        xvar.walls_color = 0xFF000000 | random.randint(0, 0xFFFFFF)
        color: int = xvar.walls_color
        r = (color >> 16) & 0xFF
        g = (color >> 8) & 0xFF
        b = color & 0xFF
        print(
            f"Next maze generation with color "
            f"\033[48;2;{r};{g};{b}m  0x{color:X}  \033[0m on walls"
        )
        key = 114

    if key == 114:  # 'r'
        xvar.finish_render = False
        print(f"Maze generated by seed '{xvar.seed}'")

        assert xvar.algorithm.img is not None
        xvar.algorithm.img.fill(xvar.walls_color)

        xvar.algorithm.generation = xvar.algorithm.backtracking_generate(
            xvar.seed
        )
        xvar.seed = random.randint(0, 10000)


def rendering_loop(xvar: XVar) -> None:
    """Render the maze generation process and update the window image."""
    if not xvar.is_running:
        close_window(xvar)
        return

    assert xvar.algorithm is not None

    for _ in range(10):
        try:
            next(xvar.algorithm.generation)
        except StopIteration:
            try:
                if xvar.algorithm.draw_generation is not None:
                    next(xvar.algorithm.draw_generation)
            except StopIteration:
                xvar.finish_render = True

    assert xvar.algorithm.img is not None

    xvar.mlx.mlx_put_image_to_window(
        xvar.mlx_ptr,
        xvar.window,
        xvar.algorithm.img.ptr,
        0,
        0
    )


def main() -> None:
    """Initialize the program, load the maze, and start the MLX event loop."""
    xvar = XVar()
    xvar.setup("config.txt")

    assert xvar.img is not None
    xvar.img.fill(0xFF000000)

    xvar.mlx.mlx_key_hook(xvar.window, gere_key, xvar)
    xvar.mlx.mlx_hook(xvar.window, 33, 0, close_window, xvar)
    xvar.mlx.mlx_loop_hook(xvar.mlx_ptr, rendering_loop, xvar)
    xvar.mlx.mlx_loop(xvar.mlx_ptr)


if __name__ == "__main__":
    main()
