from .rendering.images_utils import ImgData, draw_way
from mlx import Mlx
from src.maze_generator.MazeGenerator import MazeGenerator
from src.maze_generator.MazeAlgorithms import MazeAlgorithms
from src.maze_generator import Position
from typing import Generator
import sys
import random


class XVar:
    """Structure for main vars"""

    def __init__(self, file_path: str) -> None:
        self.mlx: Mlx = Mlx()
        self.mlx_ptr = self.mlx.mlx_init()
        self.window: int = None
        self.maze: MazeGenerator = MazeGenerator(file_path)
        self.buffer_img: ImgData = ImgData(
            self.mlx, self.mlx_ptr,
            (self.maze.width * 16) + 32,
            (self.maze.height * 16) + 32
        )
        self.algorithm: MazeAlgorithms = MazeAlgorithms(
            self.maze, self.buffer_img
        )
        self.seed: int = random.randint(0, 100)
        self.finish_render: bool = False
        self.walls_color: int = 0xFF000000


def close_window(xvar: XVar) -> None:
    xvar.mlx.mlx_destroy_window(xvar.mlx_ptr, xvar.window)
    xvar.mlx.mlx_loop_exit(xvar.mlx_ptr)


def gere_key(key: int, xvar: XVar) -> None:
    if key == 115: # 's':
        if not xvar.finish_render:
            return 0
        while True:
            try:
                xvar.seed = int(input("Enter a seed: "))
                break
            except Exception:
                print("Seed must be an integer number!")
        key = 114

    if key == 114:  # 'r'
        if not xvar.finish_render:
            return 0
        xvar.finish_render = False
        print(f"Maze generated by seed \'{xvar.seed}\'")
        xvar.algorithm.buffer_img.fill(xvar.walls_color)
        xvar.algorithm.generation = xvar.algorithm.backtracking_generate(
            xvar.seed
        )
        xvar.seed = random.randint(0, 100)

    elif key == 106:  # 'j'
        xvar.walls_color = 0xFF000000 | random.randint(0, 0xFFFFFF)
        color: int = xvar.walls_color
        r = (color >> 16) & 0xFF
        g = (color >> 8) & 0xFF
        b = color & 0xFF
        print(
            f"Next maze generation with color "
            f"\033[48;2;{r};{g};{b}m  0x{color:X}  \033[0m on walls"
        )

    return 0


def rendering_loop(xvar: XVar) -> None:
    try:
        for _ in range(5):
            next(xvar.algorithm.generation)
    except StopIteration:
        try:
            for _ in range(5):
                next(xvar.algorithm.draw_generation)
        except StopIteration:
            xvar.finish_render = True
            pass

    xvar.mlx.mlx_put_image_to_window(
        xvar.mlx_ptr, xvar.window, xvar.algorithm.buffer_img.ptr, 0, 0)


if __name__ == "__main__":
    xvar = XVar("config.txt")

    # Windows creation
    try:
        xvar.window = xvar.mlx.mlx_new_window(
            xvar.mlx_ptr,
            (xvar.maze.width * 16) + 32,
            (xvar.maze.height * 16) + 32,
            "a_maze_ing")

        if xvar.window == None:
            raise Exception("Can't create window!")
    except Exception as e:
        print(f"Error Win create: {e}", file=sys.stderr)
        sys.exit(1)
    xvar.buffer_img.fill(0xFF000000)

    xvar.mlx.mlx_key_hook(xvar.window, gere_key, xvar)

    xvar.mlx.mlx_hook(xvar.window, 33, 0, close_window, xvar)

    xvar.mlx.mlx_loop_hook(xvar.mlx_ptr, rendering_loop, xvar)
    xvar.mlx.mlx_loop(xvar.mlx_ptr)

    xvar.mlx.mlx_release(xvar.mlx_ptr)
